server:
  port: 8888

spring:
  application:
    name: config-service #해당 서비스의 이름 (다른 서비스에서 Config Service)
  cloud:
    config:
      server:
        git: #설정 파일을 저장하는 서버로 Git을 활용
          uri: 'https://github.com/taegung/config-repository.git'
          default-label: main
          timeout: 5